name = "Learn"
version = "0.1.0"
defaultTargets = ["learn"]

[[lean_lib]]
name = "Learn"

[[require]]
name = "veil"
git = "https://github.com/verse-lab/veil.git"
rev = "main"

[[lean_exe]]
name = "learn"
root = "Main"
